[package]
name = "nonzero-const-param"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
zerocopy = { version = "0", optional = true }
